### ISSUE TITLE
{Hacktober Fest 2024 }- Add Unit Tests for Word Scramble Game

### ISSUE THREAD

**Issue by bijiyiqi2017** [bijiyiqi2017/dragon24#14]
### Description:
As part of Hacktober Fest 2024, we invite contributors to enhance our word scramble web game by creating simple unit tests using **Jest**. This will help ensure key functionalities are working as intended and improve overall code quality.

### Tasks:
1. **Fork the Repository:**
   - Click the “Fork” button at the top right of this repository page to create a personal copy.

2. **Clone the Repository:**
   - Open your terminal (or Git Bash) and run:
     ```bash
     git clone https://github.com/YOUR_USERNAME/REPO_NAME.git
     ```
   - Replace `YOUR_USERNAME` with your GitHub username and `REPO_NAME` with the name of the repository.

3. **Navigate to the Project Directory:**
   - Change into the project directory:
     ```bash
     cd REPO_NAME
     ```

4. **Create a New Branch:**
   - Create a new branch for your changes:
     ```bash
     git checkout -b add-unit-tests
     ```

5. **Create Unit Tests:**
   - Write a few essential unit tests for key functionalities of the word scramble game using Jest.
   - Focus on normal cases; edge cases are optional.

6. **Add Comments in the Tests:**
   - Provide brief comments explaining the purpose of each test.

7. **Test Locally:**
   - Run your tests locally to ensure they pass using the command:
     ```bash
     npm test
     ```

8. **Take Screenshots:**
   - Capture a screenshot of the test results showing the tests passing.

9. **Commit Your Changes:**
   - Stage your changes and commit:
     ```bash
     git add .
     git commit -m "Add unit tests for word scramble game"
     ```

10. **Push to Your Fork:**
    - Push your changes to your forked repository:
      ```bash
      git push origin add-unit-tests
      ```

11. **Submit a Pull Request:**
    - Go to the original repository and click on the “New Pull Request” button. Include the screenshot in your pull request description.

### Suggested Testing Scope:
- **Word Generation:** Test that the function generates a valid word from the list.
- **Scrambling Logic:** Ensure the scrambling function produces a valid scrambled word.

### Resources for Jest:
- [Jest Documentation](https://jestjs.io/docs/getting-started): Official documentation to get started with Jest.
- [Jest Tutorial for Beginners](https://www.freecodecamp.org/news/jest-testing-tutorial-beginners/): A concise tutorial for understanding Jest.
- [Example Tests in Jest](https://jestjs.io/docs/using-matchers): Overview of different matchers to help write tests effectively.

### Additional Notes:
- **Focus on Simplicity:** Aim for clarity and simplicity in your tests. You don’t need to cover everything!
- We encourage you to aim for at least 80% test coverage.
- Please refer to the [README](LINK_TO_README) for project details and the [CONTRIBUTING](LINK_TO_CONTRIBUTING) guide for best practices when submitting your contributions.
- Reach out if you have any questions or need assistance via our [Slack channel/Discord server].

### Note for Contributors:
This issue is primarily aimed at contributors who have not submitted any pull requests during Hacktober Fest 2024. We want to encourage a diverse group of participants!
If this issue remains open after October, previous contributors are also welcome to participate, as we aim to offer as many people as possible the opportunity to contribute to this challenge.

### Optional: Star the Repository
- If you enjoy this project, please consider **starring** the repository! Here’s why:
  - **Visibility:** Starring helps others discover the project, increasing community engagement.
  - **Support:** It shows appreciation for the maintainers and contributors, encouraging continued development and support.
  - **Updates:** Starring allows you to follow updates, making it easier to keep track of changes and new features.

### Checklist:
- [ ] Forked the repository
- [ ] Cloned the repository
- [ ] Created tests
- [ ] Ran tests locally
- [ ] Added comments
- [ ] Took screenshots
- [ ] Submitted a pull request
- [ ] Starred the repository (optional)
